language: python
python:

  - "2.7"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

script:

  - coverage run --omit=*.virtualenvs*,*virtualenv* codes/0-welcome/code/0-welcome.py test
  - coverage run --omit=*.virtualenvs*,*virtualenv* codes/1-basics/basic_math_operations/code/basic_math_operation.py test
  - coverage run --omit=*.virtualenvs*,*virtualenv* codes/1-basics/variables/code/variables.py test
  - coverage run --omit=*.virtualenvs*,*virtualenv* codes/2-basics_in_machine_learning/linear_regression/code/linear_regression.py test
  - coverage run --omit=*.virtualenvs*,*virtualenv* codes/2-basics_in_machine_learning/linear_svm/code/linear_svm.py test
  - coverage run --omit=*.virtualenvs*,*virtualenv* codes/2-basics_in_machine_learning/logistic_regression/code/logistic_regression.py test
  - coverage run --omit=*.virtualenvs*,*virtualenv* codes/2-basics_in_machine_learning/multiclass_svm/code/multiclass_svm.py test




after_success:
  coveralls

sudo: enabled
dist: trusty
